### ISSUE TITLE
books: check all the conditional values

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#168]
After working with real life data we discovered inconsistencies and unchecked values. 
In order to avoid migrating inconsistencies to a new db, there is a need to cross check all the values which are parameters to conditional statements in the migration rules:

- [x] 916, 869, 595 -> acquisistion_cources

- [x] 980, 690, 697 -> collections and document types

- [x] 100 and 700 -> authors roles
- [x] 720 -> authors
- [x] 110, 710 -> corporate authors, collaborations

- [x] 020 -> isbns

- [x] 0247, 035, 036 -> external system identifiers and DOIs

- [x] 037, 088 -> report numbers and arxiv eprints

- [x] 050_4, 080, 08204, 084, 082 with subfields and identifiers -> subject_classification

- [x] 084 -> keywords (additional library)

- [x] 242__n, 246__p -> books series (242__n might be a typo, most likely refers to 246__n)

- [x] 536 -> funding info

- [x] 540 -> licenses

- [x] 542 -> copyrights

IMPORTANT NOTE: most of the unexpected values should be visible during data cleaning as an exception but we should still check the cases, where we migrate spelling mistakes (value->value).

HINT: to check possible values use this script (https://gitlab.cern.ch/AIGROUP-cds-admin/production_scripts/blob/master/cds/get_fieldvalues_books.py)

- [ ] Retrieve the rules that have not been implemented from the excel file
- [ ] Run the migrator script on different data sets (ask later)

**Comment by agentilb** [comment]
How do you want to handle this? Will you provide us with lists of problems?
