### ISSUE TITLE
Books: clean 035 (slac, spires, slacconf)

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-dojson#169]
There are currently several records that contain only slac/spires IDs but no inspire ones.

- [x] Only slacconf: http://cds.cern.ch/record/528756
- [x] Only slacconf: http://cds.cern.ch/record/833200
- [x] Only slacconf: http://cds.cern.ch/record/423699
- [x] Only slacconf: http://cds.cern.ch/record/425462
- [x] Only slacconf: http://cds.cern.ch/record/558220
- [x] Only slacconf: http://cds.cern.ch/record/561119
- [x] Only slacconf: http://cds.cern.ch/record/431284
- [x] Only slacconf: http://cds.cern.ch/record/705952
- [x] Only slacconf: http://cds.cern.ch/record/585470
- [x] Only slacconf: http://cds.cern.ch/record/607566
- [x] Only slacconf: http://cds.cern.ch/record/612477
- [x] Only slacconf: http://cds.cern.ch/record/486855
- [x] Only slacconf: http://cds.cern.ch/record/1012141
- [x] Only slacconf: http://cds.cern.ch/record/705915
- [x] Only slacconf: http://cds.cern.ch/record/585479
- [x] Only slacconf: http://cds.cern.ch/record/503602
- [x] Only slacconf: http://cds.cern.ch/record/905826
- [x] Only slacconf: http://cds.cern.ch/record/1044066

**Comment by agentilb** [comment]
Ok, all the records have been corrected. There is no more records with SLACCONF and non CNUM.
