### ISSUE TITLE
Books: conference_information as one dictionarly, not a list

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-dojson#172]
The records that we are migrating now will only have one `111` tag, corresponding to one conference. The data model should be updated to reflect this.
Agreed with @agentilb

**Comment by ludmilamarian** [comment]
Currently I found a few records that have multiple `111` tags:

https://cds.cern.ch/record/2287947/export/hm?ln=en
https://cds.cern.ch/record/2287946/export/hm?ln=en
https://cds.cern.ch/record/2213091/export/hm?ln=en
https://cds.cern.ch/record/2196657/export/hm?ln=en
https://cds.cern.ch/record/2040772/export/hm?ln=en
https://cds.cern.ch/record/2008104/export/hm?ln=en
https://cds.cern.ch/record/2007747/export/hm?ln=en
https://cds.cern.ch/record/1630674/export/hm?ln=en
https://cds.cern.ch/record/1630664/export/hm?ln=en


@agentilb ca these be fixed so that they only have one `111` field? In this way we know that they will be ok for the migration.

**Comment by agentilb** [comment]
I've cleaned those records, in many case the 111 should have been a 711 (parallel title of the conference). 

@ludmilamarian could you check as well if we have proceedings records with 2 different CNUM (035 where 035__9:INSPIRE-CNUM)?

**Comment by ludmilamarian** [comment]
@agentilb these are the recids that have more than one `inspire-cnum`:

**Comment by kprzerwa** [comment]
solved with flexible identifiers field
