### ISSUE TITLE
Modifications needed in the migration rules

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-dojson#179]
- [x] New rule to be added: Ignore field 541__ $$9
- [x] New rule to be added: Ignore subfield 082**$$2 (whatever are the indicators)
- [x] New rule to be added: 
700__ $$0 and 100__ $$0 -> authors/id.yml
               - If AUTHOR|(CDS) -> schema=CDS
               - if AUTHOR\|(SzGeCERN) -> schema=CERN

- [x] Modification needed: The following rule was not well describe in the Google docs
If 0247_ $$2:ASIN
      $$a -> external_system_identifiers/value 
      $$2 ->external_system_identifiers/schema 
(The .yml needs to be modified: add ASIN in the list of schema.)

- [x] Question: Is 700__ $$9#BEARD# necessary? 
- [x] Question: The rule 520__ $$9 -> abstract/source doesn't seem to be implemented. Could you check?
- [x] Question: It seems the accents are not properly interpreted, but this is maybe just a display problem? see ex. http://books-migrator-dev.web.cern.ch/results/record/2649010

**Comment by ludmilamarian** [comment]
For 082, I have found these possible combinations:
* `082002`
* `082042`
* `082__2`
* `0820_2`

**Comment by ludmilamarian** [comment]
Indeed, 520__9 was missing, I have added it.

**Comment by ludmilamarian** [comment]
@agentilb regarding the ASIN: usually the external system identifier is in 035, but is it correct that it can also be in 0247, in case `0247_2:ASIN`?

**Comment by ludmilamarian** [comment]
@agentilb 700__9:#BEARD# means that the ID was computed by a script and it might not be 100% correct. I would suggest to keep it, so we know that the ID information should be taken with a grain of salt. Does this seem ok for you?

**Comment by agentilb** [comment]
Yes, I'm not sure why the ASIN was stored in 024, but it is obviously in the External identifiers category. 
I don't think there is other case in 024 where we find external identifier (except DOIs).

**Comment by agentilb** [comment]
Ok for #BEARD#, but then we should find where to store this information it in the data model. I'm not sure there is a place for the time being.

**Comment by agentilb** [comment]
Regarding: 700__9#BEARD#, we could add a "curated_relation" property to:
cds-dojson/cds_dojson/schemas/records/books/ymls/elements/id.yml
When #BEARD#, it curated_relation -> false. 
Is this the meaning of this information?

**Comment by agentilb** [comment]
Additional modifications to be done in the migration rules and data model:

- [ ] Modify rule: Ignore 541__9 whatever the value is, it seems it some cases, it is not ignored and appears in the lost date fields column.

- [ ] Add rule: 300__a when the value is not fully numeric, the value should go in the entity: public_notes with, if possible, the string "Physical description:" in front.  
-> This information will be needed for the migration (mostly for the volumes), and might be deleted afterwards, since this information should be retrievable in different ways with the new structuration of data. 

- [ ] Add rule: ignore field 694__a and 694__9

- [ ] Add rule: 
For standards only (690C:STANDARD), rule for 246__a is correct, but the rule for 246__$$b is missing: 246__$$b -> title_translations/subtitle

- [ ] Modify rule:
For books (690C:BOOK), rule for 246__a is incorrect. It shouldn't go in title_translations/subtitle as for the standards. 
The correct rule is: 
246__$$a -> title.yml/title
246__$$b -> title.yml/subtitle
This field correspond to a related title. 
In order to distinguish the "related" titles from the "main" title. I suggest we add a property to title.yml
related_title:
type: boolean
When 245__$$a/246__$$b -> related_title:false
When 246__$$a/246__$$b -> related_title:true
So we will be able to distinguish the main title to display first. 

- [ ] Question: in some records, like this one:
http://books-migrator-dev.web.cern.ch/results/record/2640220
This entity is displayed, always with value "null". 
"original_source": null, 
But I cannot retrieve it in the ymls. Can you let me know where it is, and what is the corresponding rule?

**Comment by kprzerwa** [comment]
> Question: in some records, like this one:
> http://books-migrator-dev.web.cern.ch/results/record/2640220
> This entity is displayed, always with value "null".
> "original_source": null,
> But I cannot retrieve it in the ymls. Can you let me know where it is, and what is the corresponding > rule?

The general rule exists for all the records, but not for books specifically. Would you like to create a rule in this case or ignore field?

**Comment by agentilb** [comment]
What information should be in this field? Because there is already acquisition_source in the model. I just wanted to check what it is for, in order to avoid information duplication.

**Comment by kprzerwa** [comment]
@agentilb the general rule is taking the data from 541__e field. Can you specify what does it refers to in case of books?

**Comment by agentilb** [comment]
For Books and Proceedings, we do not use 541__e:
https://cds.cern.ch/search?ln=en&cc=Books+%26+Proceedings&sc=1&p=541__e%3A%27*%27&action_search=Search&op1=a&m1=a&p1=&f1=&c=Books&c=Proceedings&c=Standards&c=Design+Reports&wl=0
But I see it is used for multimedia.
