### ISSUE TITLE
ignore 541__9

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#183]
Modify rule: Ignore 541__9 whatever the value is, it seems it some cases, it is not ignored and appears in the lost date fields column.

**Comment by kprzerwa** [comment]
@agentilb could you provide a case in which this field is not ignored please?  because it is specified in the code it should be ignored, so I need to check on the examples

**Comment by agentilb** [comment]
Indeed, it doesn't happen for all record. For example this one: 1529465
See: 
http://books-migrator-dev.web.cern.ch/results

**Comment by kprzerwa** [comment]
@agentilb can you also check for cases when it is properly ignored?

**Comment by agentilb** [comment]
Ex: https://cds.cern.ch/record/2654497/export/hm?ln=en
http://books-migrator-dev.web.cern.ch/results/record/2654497

Here everything works. 
The examples I found where it doesn't work are examples that are not in the collection: BOOKSHOP. Can it be linked?
