### ISSUE TITLE
modify rule 246__a

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#187]
(related to #186)
For books (690C:BOOK), rule for 246__a is incorrect. It shouldn't go in title_translations/subtitle as for the standards.
The correct rule is:
246__$$a -> title.yml/title
246__$$b -> title.yml/subtitle
This field correspond to a related title.
In order to distinguish the "related" titles from the "main" title. I suggest we add a property to title.yml
related_title:
type: boolean
When 245__$$a/246__$$b -> related_title:false
When 246__$$a/246__$$b -> related_title:true
So we will be able to distinguish the main title to display first.

**Comment by agentilb** [comment]
Indeed, it was a typo. Sorry...

**Comment by kprzerwa** [comment]
update: 
BOOKS:
```
246__$$a -> title.yml/title
246__$$b -> title.yml/subtitle
if 246__$$a exists -> title.yml/is_alternative -> true  
245__$$a -> title.yml/title
245__$$a -> title.yml/subtitle
```
STANDARDS
```
246__$$a -> title_translations/title
246__$$b -> title_translations/subtitle
245__$$a -> title.yml/title
245__$$a -> title.yml/subtitle
```
