### ISSUE TITLE
I think the default language for a translated title should be `fr`, @agentilb WDYT?

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#191]
I think the default language for a translated title should be `fr`, @agentilb WDYT?

_Originally posted by @ludmilamarian in https://github.com/CERNDocumentServer/cds-dojson/diffs_

**Comment by agentilb** [comment]
Well this is a bit more complex...For the books (242), the translated title is used when the original title is in another language than English, so translated title is English.

For Standards, in most cases, we have the English title is 245 and the translated French title in 246, so here we can by default put Fr for the translated titles.

**Comment by kprzerwa** [comment]
for clarity: 
books: `242` -> default language `en`
standards: `245` english title
                       `246` -<default language `fr`

but I have found standards records in which the tile is for example german, @agentilb  do you have any way of identifying when the title is not default french?

**Comment by agentilb** [comment]
Hi @kprzerwa 
Ok for the books.
For the standards, indeed, normally 245 is 'eng' (and the first 041 should be 'eng'), then 246 is in most cases 'fra' (in this case, the second 041 should be 'fra'), if 246 is 'ger', the second 041 is 'ger'. It can happen that there are 3 041, so 1 245 and 2 246. 
Is it easy to use this information?
