### ISSUE TITLE
separate 245 field as title.title object

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#192]
the main title should be mandatory retrieved from 245 and the titles stored in 246 should be translated to alternative_titles list
```
245_a -> title.title
245_b -> title.subtitle
246_a -> alternative_titles.title
246_b -> alternative_titles.subtitle
```
@agentilb we think it would be better to separate main title as an object

**Comment by agentilb** [comment]
If you believe this is easier, I agree.

**Comment by topless** [comment]
@agentilb in the `title` object, there is also a property `source`. Should this one be mapped too, or can we remove it?

**Comment by agentilb** [comment]
Hi, Indeed, we do not use it for the time being, but it is something used in Inspire (I have tried to draw the model as close as possible as the one in Inspire). Also this is something we might need in the future if we import more records from other sources. So I would let it (as in the other fields we find this property), unless you have an objection? 

Anne

**Comment by topless** [comment]
Hey there @agentilb, no objections at all, we can leave it in the schema as is now, but since there is no rule to map it, it will never appear in the record.

**Comment by agentilb** [comment]
hi, indeed there is no rule because we do not use it for the time being (for books and proceedings), but we will be able to use this property in the future for new records, right?
