### ISSUE TITLE
Add rule 695__ when $$9LANL EDS

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-dojson#198]
For 695__ when $$9LANL EDS -> $$a should be stored in: arxiv_eprints/categories

This information is merged with 037 when $$9arXiv. If there is already a value in 037__c that goes in (arxiv_eprints/categories), the 695__a is added to the list (removing if possible the duplicated information).

**Comment by kprzerwa** [comment]
@agentilb just to specify: 
when `695__9` == `LANL EDS` then `695__a` --> arxiv_eprints/categories
if `695__a` already in the list added by `037__c` then remove duplicates (am I right?)

**Comment by agentilb** [comment]
@kprzerwa yes, this is correct!

**Comment by kprzerwa** [comment]
@agentilb what if one record has more than one arXiv_eprints (it's a list), to which element of the list should I attach the category from 695__a?

**Comment by kprzerwa** [comment]
also, I see that this field is in articles and preprints not in the books, nor standards, does it concern the current migration?

**Comment by agentilb** [comment]
Hi @kprzerwa there are some 140 cases in the books and proceedings. So yes, it concerns the current migration. 
ex: https://cds.cern.ch/record/2240869?ln=en

**Comment by kprzerwa** [comment]
@agentilb sorry I had to missed those records somehow.  In this case, can you please take a look on my previous question? And could you provide the examples of those records?

**Comment by agentilb** [comment]
Hi @kprzerwa, the cases where there are several arXiv numbers for one document should be really small. In those cases, I'm afraid we need to do the mapping manually. Do you have an idea of the number of cases?

**Comment by topless** [comment]
Hello @agentilb I am working on the aforementioned rule, what is the case for rule 695__ when its not  $$9LANL EDS? Should I just ignore it?

**Comment by agentilb** [comment]
Normally, there is no other value (for the Books&Proceedings), but in case there is, please ignore.
