### ISSUE TITLE
Books: Missing rules

### ISSUE THREAD

**Issue by equadon** [CERNDocumentServer/cds-dojson#206]
- [x] `035__z` Duplicate value of `035__a`? - https://cds.cern.ch/record/1475225
- [x] `041__h` Language - https://cds.cern.ch/record/1533424
- [x] `050__a` Unknown - https://cds.cern.ch/record/995202
- [x] `246__i` Key for `246__a` (type of title)? - https://cds.cern.ch/record/262314
- [x] `300__b` Unknown - https://cds.cern.ch/record/2671077
- [x] `440_3a` Subtitle? - https://cds.cern.ch/record/1533513
- [x] `5208_a` Rest of the abstract? - https://cds.cern.ch/record/2622749
- [x] `541__h` Price? - https://cds.cern.ch/record/789045
- [x] `690__c` Unknown - https://cds.cern.ch/record/2621646
- [x] `8564_8` Unknown - https://cds.cern.ch/record/2624270
- [x] `8564_s` Unknown - https://cds.cern.ch/record/2624270
- [x] `8564_x` Unknown - https://cds.cern.ch/record/2624270
- [x] `900__s` Unknown - https://cds.cern.ch/record/790764
- [x] `900__u` Filename? - https://cds.cern.ch/record/790764
- [x] `900__y` File description? - https://cds.cern.ch/record/790764

**Comment by kprzerwa** [comment]
Dear @agentilb ! We have found the rules that have not been specified (the list above). Can you let us know what should we do in those cases?

**Comment by agentilb** [comment]
Hi @kprzerwa,

`041__h`, `300__b`, `440_3a`, `5208_a`, `690__c`, `900__s`, `900__u` and `900__y`: those were mistakes, they have been cleaned, no need for a rule. 

`541__h`: to be ignored, the information is not kept in the new model. 

`8564_8`, `8564_x` and `8564_s`: those subfields are created by CDS when we attach a file to a record. I'm not sure what this refers to, if and where it should be stored. 

`035__z`: this can be ignored. 

`050__a`: the value should be stored in subject_classification/value, schema:LOC

`246__i`: I come back to you later on that field.
