### ISSUE TITLE
books: values for collections and document types

### ISSUE THREAD

**Issue by equadon** [CERNDocumentServer/cds-dojson#209]
Some `document_type`s were discarded (fixed in #208) but we should go over the possible values for collections and document types so they are classified properly.

Possible values for `690C_a` (minus the one shared with `980__a`):
```
BOOKSUGGESTION
DESIGN REPORT
DIDACTICLIBRARY
EGEEPUB
EGEETR
EUCARD
EUCARD2
EUCARDBOO
EUCARDCON
HIEISOLDEPROJECTNOTE
INTNOTE
INTNOTEALEPHPRIV
LHCCPUBL
LHCPROJECTREPORT
MASSTEV
MASSTEVPUB
MOVINGIMAGES
OTHER SUBJECTS
POSTER
PRIVLHCC
PUBLATS
PUBLCARE
PUBLHIE-ISOLDE
PUBLLEPC
PUBLLHCC
PUBLLHCPROJ
PUBLPSCC
PUBLSPSC2
PUBLTCC
SCICOM
SLHCPROJECTREPORT
TALK
UNILHC
YELLOW REPORT
```

Possible values for `980__a`:
```
ACAD
ALICE_PAPERS
ALICE_REPORTS
ARC0203
ARTICLE
ATLAS_PAPERS
ATLAS_REPORTS
BOOK
BOOKCHAPTER
CERN
CLINOT
CMS_REPORTS
CONFERENCE
CONFERENCEPAPER
COUNCIL
DUMMY
HIE-ISOLDE-PROJECT-NOTES
INTNOTEHIE-ISOLDEPUBL
LEGSERLIB
LHCB_REPORTS
NOTE
PAULISCIENTIFICBOOK
PECFA
PERI
PERIDUMP
PERITEMP
PREPRINT
PROCEEDINGS
REPORT
SCICOMMPUBLLHCC
SCICOMMPUBLPHIII
STANDARD
THESIS
VIDEOARC
```

**Comment by agentilb** [comment]
Hi @equadon, 

I've done some cleaning on those indicators. 
Among what remains, we have many types of information: 

**1) Indicators used to define a collection in CDS** (mostly used for the "CERN Scientific Output" but we find them in the Books & proceedings for records where we have a physical copy in the Library. We do not need those indicators on our side, but they are used to define collections in CDS. 

690C__ | EGEEPUB | collection: EGEE
690C__ | EGEETR | collection: EGEE
690C__ | EUCARD | collection: EUCARD
690C__ | EUCARD2 | collection: EUCARD
690C__ | EUCARDBOO | collection: EUCARD
690C__ | EUCARDCON | collection: EUCARD
690C__ | HIEISOLDEPROJECTNOTE | Used for collections?
690C__ | INTNOTEALEPHPRIV | Collection: ALEPH Note
690C__ | LHCCPUBL | Used for collections?
690C__ | LHCPROJECTREPORT | Used for collections?
690C__ | MASSTEV | collection: MassTeV
690C__ | MASSTEVPUB | Used for collections?
690C__ | PRIVLHCC | Used for collections?
690C__ | PUBLATS | Used for collections?
690C__ | PUBLCARE | Used for collections?
690C__ | PUBLHIE-ISOLDE | Used for collections?
690C__ | PUBLLEPC | Used for collections?
690C__ | PUBLLHCC | Used for collections?
690C__ | PUBLLHCPROJ | Used for collections?
690C__ | PUBLPSCC | Used for collections?
690C__ | PUBLSPSC2 | Used for collections?
690C__ | PUBLTCC | Used for collections?
690C__ | SCICOM | Used for different collections
690C__ | SLHCPROJECTREPORT | Collection: sLHC Project Reports
690C__ | UNILHC | Collection: UNILHC

980__ | ALICE_PAPERS | Collection: ALICE Papers
980__ | ALICE_REPORTS | Collection: ALICE_REPORTS
980__ | ATLAS_PAPERS | Collection: ATLAS Papers
980__ | ATLAS_REPORTS | Collection: ATLAS Reports
980__ | CLINOT | Used for collections?
980__ | CMS_REPORTS | Collection: CMS Reports
980__ | HIE-ISOLDE-PROJECT-NOTES | Collection: HIE-ISOLDE Project Notes
980__ | INTNOTEHIE-ISOLDEPUBL | Used for collections?
980__ | LHCB_REPORTS | Used for collections?
980__ | PECFA | Collection: Plenary ECFA
980__ | SCICOMMPUBLLHCC | Used for collections?
980__ | SCICOMMPUBLPHIII | Used for collections?

**2) Document types that remain**

PROCEEDINGS
BOOK
STANDARD

**3) The other document types are being cleaned from the set of documents to be migrated, we will stick with the 3 document types mentioned above:** 

CONFERENCE 
ARTICLE
BOOKCHAPTER
CONFERENCEPAPER
NOTE
PREPRINT
REPORT
THESIS
ACAD
TALK
INTNOTE

**4) Then remain "indicators" (or "tags" or any other name you think is better) that we would like to keep:**

a) _To be able to facet some parts of the collection:_ 

DIDACTICLIBRARY -> Didactic library
BOOKSUGGESTION -> Books imported from Amazon not yet acquired
LEGSERLIB -> Legal Service Library
BOOKSHOP -> Books included in the bookshop
DESIGN REPORT -> Collection of Technical design reports that belong in part to the CERN scientific output and that also contains documents available physically in the Library. 
YELLOW REPORT -> Collection of Yellow reports (it belongs to the CERN scientific output but all the records from this collection contain documents available physically in the Library). 

b) _Or to define specific separate book collections:_ 
- PAULISCIENTIFICBOOK (Collection of books which belong to the archives, not to be mixed with the Library collection) 
- ENGLISH BOOK CLUB (collection of books belonging to the English book club)

I planned to put those indicators in the field "_collection" in the data model. But we can of course discuss if you believe there is a better way to store this information. 

5) Some indicators I couldn't find in the existing collections to be migrated, could you let me know the records where you found them? 

DUMMY
VIDEOARC
PERI
PERIDUMP
PERITEMP
ARC0203

**Comment by kprzerwa** [comment]
to follow up after last meeting
