### ISSUE TITLE
adjust rules after schema cleaning

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#214]
If there is a rule existing for dropped fields, move it to separate file because it might be useful in further migration to RDM
- [x] acquisition source/datetime - dropped for now, estabilished that we can pass it as created when migrating the record (916__w, 595__a)
- [x] document_types -> change the format to string, as documents cannot have many types at the same time
- [x] record_affiliation/value (901__a) dropped
- [x] related records/edition 775__b dropped but must be represented when resolving the relation (create a ticket in cds-books for that)
   775__c gives the relation type @agentilb can you confirm? -  we need to know which field says that the relation is about language or edition
- [x] related records/edition 775__b dropped but must be represented when resolving the relation (create a ticket in cds-books for that)    
- [x] related_records/year dropped - should be resolved as a field of relation
- [x] additional_subject_categories - dropped 65017 65027
- [x] cds_subject_categories - dropped 65017
- [x] conference_info/conference_dates dropped as a redundant into ( 111__d)
- [x] conference_info/conference_series_number moved to conference_info/series/number
- [x] conference_info/year dropped
- [x] conference_info/ removed `conference` from subfield names 
- [x] editions change type to string  from array
- [x] preprint_date -269__c dropped
- [x] publication_info/ curated_relation dropped
- [x] publication_info/ material dropped
- [x] publication_info/ parent_isbn dropped 773__z
- [x] publication_info/ parent_record dropped
- [x] publication_info/ parent_report_number dropped 773__r
- [x] publication_info/pubinfo_freetext renamed to `note`
- [x] thesis_info dropped

**Comment by agentilb** [comment]
@kprzerwa for 775, the relation is given by $$b and or $$c 

for example, you have: 
https://cds.cern.ch/record/2674589?ln=en
-> it shows the different editions and the corresponding years. 

For the standard, you only have the year: 
https://cds.cern.ch/record/2299964?ln=en

The language will also be in $$b
ex: https://cds.cern.ch/record/2665531?ln=en
