### ISSUE TITLE
missing rules 

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#221]
- [x] 916__w - https://cds.cern.ch/record/2654221/export/hm?ln=en
- [x] 980__c - https://cds.cern.ch/record/2654259 marked as deleted in this field, shouldn't be 980__a?
- [x] 970__a - https://cds.cern.ch/record/262170/export/hm?ln=en
- [ ] 0248_q - https://cds.cern.ch/record/2654259 looks like type book also in DOI
- [x] 020__c - https://cds.cern.ch/record/98395/export/hm?ln=en
- [x] 901__u - https://cds.cern.ch/record/98881/export/hm?ln=en

**Comment by agentilb** [comment]
@kprzerwa here are already some information from the Library side: 
- 970__a: Include the old aleph number, we did a huge cleaning with Ludmila before she left, normally those numbers are not useful anymore. So they shouldn't be migrated. 
- 0248_q: this is a CDS field, used for the OAI feeds I guess
- 020__c: this is an acquisition information. but for the time being, it can be stored at the ebook level, in the property: private_note. 
- 901__u: this is being cleaned, should be ignored during the migration
- 916__w: this is a week and year of creation of the record, should be stored in the acquisition_source. (to be discussed)
- 980__c: all deleted records have this field 980__c:DELETED. I don't know how you want to manage the deleted records in the new systems.

**Comment by kprzerwa** [comment]
@agentilb 
- about 020__c I need to know the field that we plan to store it in the end, not temporary so we can evaluate and decide what approach would be the best for migrating it.
- for 916__w we already discussed I will keep it somewhere else in the system field, I forgot about it, because it is in a different ticket - now you reminded me
- 980__c i just wanted to know if it is always subfield _c for deleted

**Comment by agentilb** [comment]
@kprzerwa for 020__c, we need to work on the data model for acquisitions then. I have already some notes about this, I can send you something in the coming days.
