### ISSUE TITLE
020__c

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#232]
Comments about :

> 020__c: this is an acquisition information. but for the time being, it can be stored at the ebook level, in the property: private_note.
> 
> about 020__c I need to know the field that we plan to store it in the end, not temporary so we can evaluate and decide what approach would be the best for migrating it.

Please provide more information and implement the rule

**Comment by kprzerwa** [comment]
@agentilb could you please let me know what is the state of defining this rule?

**Comment by agentilb** [comment]
As discussed, let's store it in an internal note at the e-item level, with this label in front: Ebook Central price:

**Comment by kprzerwa** [comment]
decided to be ignored
