### ISSUE TITLE
Volume migration: Move volume-specific DOI and URL to 020__

### ISSUE THREAD

**Issue by equadon** [CERNDocumentServer/cds-dojson#242]
For the volume migration it would be very helpful for us if we could move the volume-specific DOIs (`0247_q`) and URLs (`8564_y`) to new subfields in `020__`. @agentilb do you think this would this be possible to do?

Related to #222

**Comment by agentilb** [comment]
Hi Niklas, It should be feasible.

**Comment by kprzerwa** [comment]
TODO: implement volumes dump into _migration field for books (now only implemented for series, reason unknown)
