### ISSUE TITLE
Migration conflicts with document schema

### ISSUE THREAD

**Issue by equadon** [CERNDocumentServer/cds-dojson#250]
Document schema validation errors and example records that caused the error:
- [x] Edition is migrated as an array (https://cds.cern.ch/record/100111)
- [x] Unexpected property `reprint` in `imprints` (https://cds.cern.ch/record/106544)
- [x] Affiliation `CERN` is not an object (https://cds.cern.ch/record/607586)
- [x] Unexpected properties in `authors`: `curated_relation` and `ids` (https://cds.cern.ch/record/1610792)
- [x] Records can have identical abstracts (conflicts with unique abstract items)

**Comment by kprzerwa** [comment]
edition should be a string, not an array

**Comment by kprzerwa** [comment]
solved
