### ISSUE TITLE
Books (Proceedings, Standards and Periodicals) rules and schemas

### ISSUE THREAD

**Issue by egabancho** [CERNDocumentServer/cds-dojson#30]
CDS specific version of https://github.com/inveniosoftware/invenio-circulation/issues/55

**Comment by egabancho** [comment]
[json.zip](https://github.com/CERNDocumentServer/cds-dojson/files/1084503/json.zip)

**Comment by ludmilamarian** [comment]
This is deprecated now, there are new task for this: #132 and #133
